name: json_converter
description: JSON converters for package:json_serializable.
version: 1.0.1
homepage: https://github.com/agilord/json_converter

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
