name: json_converter
description: JSON converters for bytes when using the json_serializable package.
version: 2.0.1
homepage: https://github.com/agilord/json_converter
topics:
  - json
  - encoder
  - bytes

environment:
  sdk: '^3.0.0'

dependencies:
  json_annotation: ^4.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.6.0
