name: json_converter
description: JSON converters for package:json_serializable.
version: 2.0.0
homepage: https://github.com/agilord/json_converter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
